openapi: 3.0.3
info:
  title: SHOP PROJECT
  version: 0.0.0
paths:
  /shop_app/billing/:
    get:
      operationId: shop_app_billing_retrieve
      tags:
      - shop_app
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: shop_app_billing_create
      tags:
      - shop_app
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: shop_app_billing_update
      tags:
      - shop_app
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /shop_app/billing/{customer_name}/:
    get:
      operationId: shop_app_billing_retrieve_2
      parameters:
      - in: path
        name: customer_name
        schema:
          type: string
        required: true
      tags:
      - shop_app
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: shop_app_billing_create_2
      parameters:
      - in: path
        name: customer_name
        schema:
          type: string
        required: true
      tags:
      - shop_app
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: shop_app_billing_update_2
      parameters:
      - in: path
        name: customer_name
        schema:
          type: string
        required: true
      tags:
      - shop_app
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /shop_app/billings/{id}/:
    get:
      operationId: shop_app_billings_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - shop_app
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: shop_app_billings_create
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - shop_app
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: shop_app_billings_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - shop_app
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /shop_app/employees/:
    get:
      operationId: shop_app_employees_retrieve
      tags:
      - shop_app
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: shop_app_employees_create
      tags:
      - shop_app
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: shop_app_employees_update
      tags:
      - shop_app
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: shop_app_employees_destroy
      tags:
      - shop_app
      security:
      - tokenAuth: []
      responses:
        '204':
          description: No response body
  /shop_app/employees/{id}/:
    get:
      operationId: shop_app_employees_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - shop_app
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: shop_app_employees_create_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - shop_app
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: shop_app_employees_update_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - shop_app
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: shop_app_employees_destroy_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - shop_app
      security:
      - tokenAuth: []
      responses:
        '204':
          description: No response body
  /shop_app/login/:
    post:
      operationId: shop_app_login_create
      tags:
      - shop_app
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /shop_app/products/:
    get:
      operationId: shop_app_products_retrieve
      tags:
      - shop_app
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: shop_app_products_create
      tags:
      - shop_app
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: shop_app_products_update
      tags:
      - shop_app
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: shop_app_products_destroy
      tags:
      - shop_app
      security:
      - tokenAuth: []
      responses:
        '204':
          description: No response body
  /shop_app/products/{id}/:
    get:
      operationId: shop_app_products_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - shop_app
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: shop_app_products_create_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - shop_app
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: shop_app_products_update_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - shop_app
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: shop_app_products_destroy_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - shop_app
      security:
      - tokenAuth: []
      responses:
        '204':
          description: No response body
  /shop_app/register/:
    get:
      operationId: shop_app_register_retrieve
      tags:
      - shop_app
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: shop_app_register_create
      tags:
      - shop_app
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /shop_app/schema/:
    get:
      operationId: shop_app_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - shop_app
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /shop_app/shops/:
    get:
      operationId: shop_app_shops_list
      tags:
      - shop_app
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Shop'
          description: ''
    post:
      operationId: shop_app_shops_create
      tags:
      - shop_app
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Shop'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Shop'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Shop'
        required: true
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shop'
          description: ''
    delete:
      operationId: shop_app_shops_destroy
      tags:
      - shop_app
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '204':
          description: No response body
  /shop_app/shops/{id}/:
    get:
      operationId: shop_app_shops_list_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - shop_app
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Shop'
          description: ''
    post:
      operationId: shop_app_shops_create_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - shop_app
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Shop'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Shop'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Shop'
        required: true
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shop'
          description: ''
    delete:
      operationId: shop_app_shops_destroy_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - shop_app
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '204':
          description: No response body
  /shop_app/stocks/:
    get:
      operationId: shop_app_stocks_retrieve
      tags:
      - shop_app
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: shop_app_stocks_create
      tags:
      - shop_app
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /shop_app/stocks/{id}/:
    get:
      operationId: shop_app_stocks_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - shop_app
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: shop_app_stocks_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - shop_app
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: shop_app_stocks_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - shop_app
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    Shop:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          writeOnly: true
        owner_name:
          type: string
          maxLength: 100
        address:
          type: string
          maxLength: 255
        contact_no:
          type: string
          maxLength: 15
        email:
          type: string
          format: email
          maxLength: 254
      required:
      - address
      - contact_no
      - email
      - id
      - owner_name
      - username
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
