# Generated by Django 4.2.5 on 2024-03-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_remove_shop_user_shop_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='owner_name',
            new_name='shop_name',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
