# Generated by Django 4.2.5 on 2024-03-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_product_pro_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_link',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
