# Generated by Django 4.2.5 on 2024-03-25 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_app.shop'),
        ),
    ]
