# Generated by Django 4.2.5 on 2024-04-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0010_billingdetails_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackFormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('shop_name', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=10)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
