# Generated by Django 4.2.5 on 2024-04-02 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0012_responsemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceVerified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.responsemodel')),
            ],
        ),
    ]
