# Generated by Django 4.2.5 on 2024-04-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0014_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='csvs/'),
        ),
    ]
